# Propertie to enabled console in web-browser
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:apptennisdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true
server:
  port: 3001